const affiliations = [
  "10th Planet Arizona",
  "10th Planet JJ",
  "7th Generation BJJ",
  "82 JIU JITSU",
  "A-FORCE SLOVAKIA",
  "A-Force BJJ",
  "A-Force Ukraine",
  "AA jiujitsu",
  "AB",
  "ADAMAS BJJ",
  "ADCC Submission Fighting Iran",
  "ADF Martial Arts Association",
  "AEG affiliation",
  "AIWI",
  "ALFA JIUJITSU ASSOCIATION",
  "ATOS HONGKONG",
  "AURUM JIU JITSU",
  "Aberdeen Combat Centre",
  "Abmar Barbosa JJ Association",
  "Absolute MMA",
  "Absoluto BJJ",
  "Abyss Jiu-Jitsu",
  "Academia de la Costa",
  "Akagi Jiu-Jitsu",
  "Akxe",
  "Alliance",
  "Alliance",
  "Alliance Gym",
  "Alliance Jiu Jitsu Indonesia",
  "Alliance Lucas Lepri",
  "Alliance Marcelo Garcia International",
  "Aloisio Silva BJJ",
  "Alpen BJJ",
  "American Killer Bees",
  "American Top Team",
  "Amos Martial Arts",
  "Anderson Goncalves BJJ",
  "Arashi Do",
  "Ares BJJ USA",
  "Arizona Combat Sports",
  "Arlans Siqueira Brazilian Jiu-Jitsu",
  "Arte Suave SA",
  "Aspinall BJJ",
  "Association Aranha Bjj Barcelona",
  "Athletic Advance",
  "Atos",
  "Atos Arizona",
  "Atos Espada Hong Kong",
  "Australia ASBJJ",
  "Australian Elite Team",
  "Australian Grappling Clubs",
  "Axis Jiu-Jitsu Academy Australia",
  "B9 Barbosa Germany",
  "BATATINHA TEAM",
  "BC",
  "BEHRING PUERTO RICO",
  "BETA Academy",
  "BHJJ",
  "BJJ COACH BRASIL",
  "BJJ Freaks Russia",
  "BJJ Globetrotters",
  "BJJ Olympia",
  "BJJ Revolution Team",
  "BLAKZ Team International",
  "BMA - Bajerski martial arts",
  "BROTHERHOOD OF PSYCHO",
  "BSTF",
  "Babalu's Iron Gym",
  "Bad Boy Training Centre",
  "Baret Submissions Association",
  "Baret Submissions Canada",
  "Berserkers Team Deutschland",
  "Big Brothers",
  "Black Dragon Kai",
  "Body of Four Team",
  "Bodyfit KC",
  "Bonsai Jiu Jitsu",
  "Born To Roll",
  "Brasa",
  "Brasa CTA",
  "Brasa New Zealand",
  "Brazilian Power Team",
  "Brazilian Top Team",
  "Brixton Capital / Seven Mile Casino",
  "Bronx Martial Arts Academy",
  "Budo Clan",
  "Budo Jiu-Jitsu Team",
  "Bushidokan",
  "Bushinkai International",
  "C Quence jiu jitsu",
  "CAPITAL USA TEAM",
  "CF24",
  "CFS BJJ",
  "CHOKE LUTA LIVRE GREECE",
  "CMJJ",
  "CRAZY TEAM",
  "CTA Arizona",
  "CXBJJ Academy",
  "Cabeça BJJ",
  "Caio Terra",
  "Caique Jiu Jitsu",
  "Canon BJJ",
  "Cantagalo International",
  "Carlos Farias BJJ",
  "Carlson Gracie Arizona",
  "Carlson Gracie Team",
  "Cascão Jiu-jitsu",
  "Cavalcanti BJJ Association",
  "Cervizzi's Martial Arts Academy",
  "CheckMat Arizona",
  "Checkmat",
  "Checkmat China",
  "Checkmat VG Team",
  "Chicago MMA",
  "Chicago Mixed Martial Arts",
  "Choke BJJ",
  "Chris Papandria Jiu Jitsu",
  "Cicero Costha Canada",
  "Clark Gracie Jiu Jitsu",
  "Cleber Jiu Jitsu",
  "Cmaa",
  "Cobra Kai",
  "Combat Base",
  "Connection Gracie JiuJitsu",
  "Core Combat Sports Rockford",
  "Corpo e Mente",
  "Cross Combat",
  "D15 ACADEMY JIU JITSU",
  "DC Fighters",
  "DJ Team",
  "Danimal BJJ",
  "David Blankenheimer BJJ",
  "De Been 100% Jiu Jitsu",
  "DeBrazil Jiu-Jitsu Academy",
  "DeVall MMA and BJJ",
  "Defend Michigan",
  "Delariva Costa Rica",
  "Demian Maia Jiu-Jitsu",
  "Detroit Jiu-Jitsu",
  "Diego Bispo",
  "Dojo Dynasty",
  "Double Five",
  "Draig",
  "Dynamix",
  "EDJ ASSOCIATION",
  "ELEVATE JIU JITSU (TEAM)",
  "East Coast Jiu Jitsu Academy",
  "East Ocean Jiu-Jitsu",
  "Ed Ramos Jiu Jitsu USA",
  "Elements BJJ",
  "Elements JJ Bahrain",
  "England",
  "Erik Paulson's CSW/CSBJJ",
  "Escapology BJJ",
  "Escola Mente e Corpo",
  "European Kombatan Association",
  "Evolution Brazilian Jiu-Jitsu",
  "Evolution Fight Team",
  "Experience Jiu-Jitsu",
  "FIGHTER JIU-JITSU",
  "FLOW'N ROLL",
  "FT Jiu jitsu",
  "Fabio Santos BJJ",
  "Fabricio International Team",
  "Falkie BJJ",
  "Faz forca team",
  "Felipe Mota",
  "Fernando Moya Jiu Jitsu",
  "Fight Club Windsor",
  "Fight Sports International",
  "Fight to win",
  "Five Elements Jiu-Jitsu",
  "Flavio Behring  Jiu Jitsu USA",
  "Flavio Behring AZ",
  "Floresta Negra Jiu Jitsu",
  "Focus JJ",
  "Focused Fight Team",
  "Foster BJJ",
  "Foundation Chicago",
  "Free-Mortals",
  "Freelance",
  "Frontline",
  "Frota Team Nogueira",
  "Full Charge BJJ",
  "G13 BJJ",
  "GD Jiu-Jitsu Association",
  "GFTeam",
  "GHBJJ/HYBRID Academy",
  "GPS Brazilian Jiu-jitsu",
  "GRBJJ",
  "GUERRILLA JIU-JITSU NEWCASTLE",
  "Galeb Brothers BJJ",
  "Geovanni's Team - PT",
  "German Top Team",
  "Gordo Jiu-Jitsu Europe",
  "Gracie Barra",
  "Gracie Barra - Draculino Czech",
  "Gracie Barra Arizona Jiu-Jitsu & Self-Defense",
  "Gracie Barra Colorado",
  "Gracie Elite Australia",
  "Gracie Gym NZ",
  "Gracie Humaita",
  "Gracie Humaita Arizona",
  "Gracie Jiu Jitsu Affiliation",
  "Gracie Team SE",
  "Gracie United",
  "Grand Union BJJ Team",
  "Grapplers Elite",
  "Grappling Panda",
  "Grateful bjj",
  "Great Britain Martial Arts Team",
  "Grinta Team",
  "Ground Control BJJ",
  "Ground Game Grenada/Cleveland",
  "Ground Pressure Team",
  "Guerilla Jiu Jitsu",
  "Guigo Jiu Jitsu International",
  "Gustavo Machado Brazilian Jiu Jitsu",
  "Gustavo Pires Siri BJJ",
  "Gymnasium",
  "HOLY CITY WARRIORS",
  "HOUSE OF ALAMEDA JIU JITSU",
  "Halavanca",
  "Headhunters Martial Arts",
  "Hill Brothers Team",
  "Hilti BJJ",
  "Hojt",
  "Hokuto BJJ",
  "HoneyBadgers",
  "IMA",
  "IMC AUSTRALIA",
  "INFIGHT",
  "INTELLIGENT TEAM UKRAINE",
  "Icon BJJ",
  "Icon Romania",
  "Igor MMA Academy",
  "Infight Canada",
  "Inglorious Grapplers",
  "Integrated Combat Centre",
  "International Koshiki Karate Federation",
  "Ireland",
  "Iron Grip Martial Arts US",
  "Itaipava BJJ",
  "Iturralde Arte Suave",
  "JCBJJ",
  "JG ACADEMY",
  "JR Team",
  "JSBJJ",
  "Jean Jacques Machado",
  "Jiu-Jitsu For Life Team",
  "Joe Hurst Brazilian Jiu Jitsu",
  "John's Gym",
  "Jones jiu-jitsu",
  "Joshua James Miller",
  "Ju Jitsu Ryu Tsunami",
  "KJ Competition Team",
  "Kane Gehling Jiu Jitsu Association",
  "Kimura",
  "Kioto Universal AZ",
  "Kita Ryu",
  "Knight Jiu-Jitsu",
  "KnuckleUp Fitness",
  "Kombat Jiu Jitsu",
  "Kore Brazilian Jiu-Jitsu Association",
  "Kyuzo Brazilian Jiu Jitsu",
  "LCCT",
  "LEAD BJJ",
  "Legends BJJ",
  "Logic",
  "Lokahi Academy",
  "Lotus Club Arizona",
  "Lotus Club USA",
  "Lovato Jiu Jitsu",
  "Ludus Alliance Russia",
  "Luiz Palhares",
  "Luta Livre Italia",
  "Luta Livre Movement",
  "Lutador BJJ - Serbia",
  "MACACO GOLD TEAM",
  "MARIO SILVA",
  "MB",
  "MGK Squad",
  "MMA CASTELLI ROMANI",
  "MMA Stop",
  "MXT Fight Academy",
  "Macaco Gold Team Ireland",
  "Mad Hatters",
  "Made4theCage BJJ",
  "Magpie Fang Jiu Jitsu",
  "Mandala Escócia",
  "Maracaba BJJ AZ",
  "Marcello Alcantar",
  "Marcelo Alonso Brazilian Jiu Jitsu",
  "Marcio Andre Jiu-Jitsu Association",
  "Marcos Escobar BJJ",
  "Marcos Nardini BJJ",
  "Marcus Soares Jiu-Jitsu Team",
  "Marra Senki Competition Team",
  "MatSide Jiu-Jitsu",
  "Mauricio Gomes Legacy",
  "Mauricio Gomes Origin Team",
  "Mauro Sergio BJJ",
  "Melone Brazilian Jiu Jitsu",
  "Mill Hill BJJ",
  "Mjölnir",
  "Modern Martial Arts",
  "Momentum Jiu Jitsu",
  "Mongrel Jiu-Jitsu and Fitness",
  "Monkey Jits",
  "Morcegao BJJ",
  "MyBJJ New Zealand",
  "MyBJJ Team",
  "NINE NINE HQ SAN DIEGO",
  "NSW University Taekwondo Club",
  "NT",
  "Natinal Jiu Jitsu association",
  "National Jiu Jitsu Association",
  "Neutral Ground",
  "New Life Jiu Jitsu Association",
  "New Zealand Top Team",
  "Next Level Brazilian Jiu-Jitsu",
  "Nexus BJJ",
  "Nick Brooks BJJ",
  "No Joke",
  "Northern Monkey Jiu Jitsu",
  "Northstar Ju Jitsu",
  "Not in use 1",
  "Nova União",
  "ON",
  "Okotoks Brazilian Jiu-Jitsu",
  "One Jiu-Jitsu",
  "One Jiu-Jitsu Arizona",
  "One Love Grappling Arts",
  "One Way",
  "Open Source Jiu-Jitsu",
  "PAGELS BRAZILIAN JUJITSU",
  "PE",
  "PWKA Federation",
  "Pablo Silva BJJ",
  "Pacific Top Team",
  "Palestra Jiu Jitsu",
  "Paraestra",
  "Paraestra Australia",
  "Paragon BJJ Arizona",
  "Paulo Filho BJJ Team",
  "Pedigo Submission Fighting",
  "Pedro Bessa BJJ",
  "Pedro Bessa BJJ Ireland",
  "Pedro Sauer Gracie Jiu Jitsu",
  "Port City MMA, LLC",
  "Pound For Pound Team",
  "Premier BJJ & Catch Wrestling",
  "Pretorian Team",
  "Pride BJJ",
  "Princeton BJJ",
  "Pro Training Brazilian Jiu-Jitsu",
  "Pura Vida BJJ",
  "QC",
  "Qazaqstan Top Team",
  "R1ngBJJ",
  "REIGN Jiu Jitsu",
  "RILION GRACIE-GRACIE ELITE TEAM",
  "RMNU ( Team Robson Moura )",
  "Ralph Gracie Jiu-Jitsu",
  "Red River BJJ",
  "Reinel Spyker Jiu-jitsu",
  "Relson Gracie",
  "Relson Gracie AZ",
  "Renato Tavares Association",
  "Renzo Gracie NY",
  "Renzo Gracie Ottawa",
  "Renzo Gracie TX",
  "Resistencia Jiu-jitsu",
  "Ribeiro Jiu-Jitsu Romania",
  "Ribeiro Jiujitsu",
  "Riberio",
  "Ricardo Almeida Association",
  "Rice Bros Association",
  "Rick Young's Black Belt Academy",
  "Rickson Gracie Jiu-Jitsu Holland",
  "Rigan Machado",
  "Rio Grappling Club",
  "Rio Grappling Club Scotland",
  "Rio Grappling Club South Africa",
  "Rising Phoenix",
  "Robert Drysdale",
  "Roberto Britto Jiu Jitsu",
  "Roberto Traven",
  "Rock City MMA LITTLE ROCK",
  "Roger Coelho BJJ",
  "Roger Gracie",
  "Roll Academy",
  "Roots Brazilian Jiu-Jitsu",
  "Round Table BJJ",
  "Roy Dean Academy International",
  "Roy Dean International",
  "Roy Harris BJJ",
  "Royal Grappling Academy",
  "Ruffhouse",
  "SAS Team USA",
  "SASA bjj",
  "SBG",
  "SBG - Straight Blast Gym",
  "SBG UK",
  "SHBJJ",
  "SIA - Sharpen Iron Academy",
  "SJJA TEAM",
  "SK",
  "SMAC",
  "SOUTHSIDE BRAZILIAN JIU-JITSU OFFICIAL",
  "Saberation",
  "Sampa Team",
  "SampaioBJJ_FCS",
  "Sapateiro Top Team",
  "Sapsan Team",
  "Satori",
  "Satsang",
  "Savarese Jiu-Jitsu Association",
  "Scotland",
  "Senna Fight Academy",
  "Shane Weaver",
  "Shaun Matthews BJJ",
  "Shawn Hammonds AZ",
  "Shokunin BJJ Association",
  "Shokunin Brazilian Jiu-Jitsu Association",
  "Shooters MMA",
  "Singapore Wrestling",
  "Smart Grapplers Brotherhood",
  "Smash Gyms",
  "Snake Pit U.S.A. Catch Wrestling Association",
  "Socius BJJ",
  "Soma Jiu-Jitsu",
  "Soul Fighters",
  "Soul Fighters Arizona",
  "Southside Brazilian Jiu-Jitsu Europe",
  "Spirit Taekwondo 'The Ultimatum'",
  "Sportschool Herbert",
  "St. Petersburg Kudo Federation",
  "Stealth BJJ",
  "StoneFight",
  "Stoneguard Team",
  "Strela",
  "Stronghold Jiu-Jitsu",
  "Subconscious BJJ",
  "Swedish Karate Kyokushinkai",
  "Synergy BJJ Indonesia",
  "TAC Team",
  "TAZ BJJ",
  "TEAM PREDADOR INTERNATIONAL",
  "TITAN BJJ",
  "TJJ School",
  "Team Balance",
  "Team Buda Bjj",
  "Team Bēsu",
  "Team Carvalho Association",
  "Team Carvalho Europe",
  "Team Concrete",
  "Team Curran",
  "Team Evolve",
  "Team FM",
  "Team Fightzone-Stockholm",
  "Team Insight",
  "Team James Clingerman",
  "Team KF Martial Arts",
  "Team Kaishin",
  "Team Kimura USA",
  "Team LDMA",
  "Team Leites",
  "Team Lloyd Irvin",
  "Team Mamute",
  "Team Mascarenas",
  "Team Mohler Affiliation ",
  "Team Neves",
  "Team ONE Jiu-Jitsu Canada",
  "Team Poseidon",
  "Team Redzovic",
  "Team Rodrigo Resende",
  "Team Ronin Brazilian Jiu-Jitsu",
  "Team Royce Gracie",
  "Team Rubão Carioca BJJ",
  "Team Ryano International",
  "Team Shawn Hammonds",
  "Team Sukata",
  "Team Sweden JJR",
  "Team Torres",
  "Team Vaghi",
  "Team West",
  "Team Wise",
  "Team Z11",
  "Team link",
  "Team-Choco",
  "The Match Champ",
  "The Tribe",
  "Titanes BJJ",
  "Tom DeBlass Association",
  "Train Hard, Be Kind",
  "Tri-force",
  "True North Jiu Jitsu",
  "Trujitsu Unified",
  "Tsunami Southern Tribes Aoteroa",
  "Tu Kaha NZ",
  "Tukaha JiuJitsu Affiliation",
  "Turkish Republic of Northern Cyprus",
  "UFC",
  "UWC UNIVERSAL WRESTLING CLUB",
  "Ucelo Martial Arts BJJ",
  "Uflacker Academy",
  "Ultimate Jiu Jitsu Union",
  "United Grappling Connection",
  "Universal Jiu Jitsu",
  "Vale Tudo",
  "Van Buren Jiu Jitsu",
  "Veneration BJJ",
  "Veterans Jiu-Jitsu",
  "ViN BJJ",
  "Victory Jiu Jitsu",
  "Vieira Jiu-Jitsu",
  "Vinny Magalhaes BJJ",
  "Vitor Shaolin",
  "Viva Zapata Jiu Jitsu",
  "Volcano BJJ",
  "WAO",
  "WAZA",
  "Wales",
  "Warwolf BJJ",
  "West Coast BJJ Association",
  "Will Machado Australasia",
  "Wisconsin 360 Jiu-Jitsu",
  "World Thai Boxing Association",
  "Wulfing Academy",
  "Yagadome",
  "Yamasaki",
  "Yogui BJJ Association",
  "Yoseikan Carlos Toyota",
  "Z",
  "ZR Team Association",
  "Zenith",
  "Zuma",
  "Beerjj",
  "Спортивный Клуб Юсуповых",
  "兴和胜柔术战队",
];

export default affiliations;
